name: Install Python Package

on:
  workflow_run:
    workflows: ["Awesome Calculator CI build"]      # Name of the first workflow
    types:
      - completed       # Triggers when the first workflow completes

jobs:
  install-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact (awesome-calculator)
        uses: actions/download-artifact@v3
        with:
          name: awesome-calculator
          path: /tmp/awesome-calculator

      - name: Install Python package from .whl file
        run: |
          cd /tmp/awesome-calculator/src/dist
          pip install *.whl       # Install the .whl file from the downloaded artifact