name: Install Python Package

on:
  workflow_run:
    workflows: ["Awesome Calculator CI build"]      # Name of the first workflow
    types:
      - completed       # Triggers when the first workflow completes

jobs:
  install-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Debugging Step: List available artifacts
      - name: List available artifacts
        run: |
          curl -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"

      # Wait for the first workflow to finish and ensure the artifact is uploaded
      - name: Sleep for 30 seconds (wait for artifact upload)
        run: sleep 30

      - name: Download artifact (awesome-calculator)
        uses: actions/download-artifact@v3
        with:
          name: awesome-calculator
          path: /tmp/awesome-calculator

      - name: unzip the artifact
        run: |
          unzip /tmp/awesome-calculator/awesome-calculator.zip -d /tmp/awesome-calculator         # Extract the zip file.

      - name: Install Python package from .whl file
        run: |
          cd /tmp/awesome-calculator/src/dist
          pip install *.whl       # Install the .whl file from the downloaded artifact